name: Aggiorna index.html

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Genera index.html
        run: python generate_index.py
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html data.json entries.json
          git commit -m "Aggiornamento automatico sito" || echo "Nessuna modifica"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/aiemas/miaf.git HEAD:main
